### ISSUE TITLE
Pushing the code

### ISSUE THREAD

**Issue by Mehrad0711** [hendrycks/outlier-exposure#1]
Hi,
Is it possible to push the rest of the code including the language modeling task?
I'm doing some related work and it would be of great help.
Thanks!

**Comment by hendrycks** [comment]
> Is it possible to push the rest of the code including the language modeling task?

Thank you for the reminder. I will do so after ICML's submission deadline.

**Comment by hendrycks** [comment]
Hopefully 78367ee addresses this concern.
