### ISSUE TITLE
code for pixelcnn++

### ISSUE THREAD

**Issue by DikshaMeghwal** [hendrycks/outlier-exposure#11]
Maybe I am not looking hard enough but I can't seem to find the code for density estimation using pixelcnn++. Can you direct me to the file for the same?

**Comment by hendrycks** [comment]
This is the code we used: https://github.com/pclucas14/pixel-cnn-pp

**Comment by matejgrcic** [comment]
Could you provide the training script or model weights after fine-tuning?
