### ISSUE TITLE
Standardisation of OOD samples

### ISSUE THREAD

**Issue by paganpasta** [hendrycks/outlier-exposure#13]
Hi,

I was looking to understand the pre-processing involved prior to generating predictions from the neural network on OOD samples for computer vision(image classification). Specifically, how the OOD-test samples are standardised. Could you shed some light on it?

Regards.

**Comment by hendrycks** [comment]
https://github.com/hendrycks/outlier-exposure/blob/master/CIFAR/test.py#L51 shows that we have the input be between [0,1] then we subtract each image channel by the training set mean and divide by the standard deviation.
