### ISSUE TITLE
Removing duplicates

### ISSUE THREAD

**Issue by sesmae** [hendrycks/outlier-exposure#15]
Hi,

In your paper, you mention that 'We remove all examples of 80 Million Tiny Images which appear in the CIFAR datasets'. I was trying to download 80 million Tinyimagenet but apparantly it is not available anymore. Instead, I am trying to use  imagenet32X32. Is there an effective way to remove duplicates of cifar10 or cifar100 from imagenet32X32 ?

**Comment by hendrycks** [comment]
A mirror of 80 Million Tiny Images is here: http://www.archive.org/download/80-million-tiny-images-2-of-2/tiny_images.bin

**Comment by sesmae** [comment]
Thank you for the link and quick response. How about removing the duplicates of cifar from it?

**Comment by hongxin001** [comment]
Hello, @sesmae Do you solve the problem? I also encounter that.
