### ISSUE TITLE
Which subset did you use for Places365 as OOD?

### ISSUE THREAD

**Issue by igormq** [hendrycks/outlier-exposure#2]
Which subset did you use for Places365 as OOD?

There are a plenty of options in the Places365 website. :)

Best,
Igor.

**Comment by hendrycks** [comment]
We used Places365-Standard (256x256) for the in-distribution. For the
source of outliers for OE, we used ImageNet-22K. Places69 (256x256) was
used during testing.

Best,
Dan Hendrycks

**Comment by igormq** [comment]
Thank you, Hendrycks! Have you used the train images (90k+) or the test images (6k+)?

**Comment by hendrycks** [comment]
I used both Places69 sets together for testing since both sets are unseen.

**Comment by weitliu** [comment]
Hi Dan. I rerun your wrn test code on CIFAR10 (no retrain or fine tune) and everything seems to be consistent except for the Places365. You mentioned that you used different subsets of Places365. Does it only apply to the case when Places365 is D_in?

If I use cifar10, here is my setting:
D_in: Cifar10
D_oe: 80m tiny images
D_test: Places69 (256x256) (my comment: it is neither Places365-Standard nor Places365-Challenge 2016. I download the dataset from http://data.csail.mit.edu/places/places_extra69/data_256_extra.tar, which is almost at the bottom of the page.)

I put the results as git diff here, comparing your git log and my new results:
-FPR95:                 17.28   +/- 1.26
-AUROC:                96.23   +/- 0.20
-AUPR:                   87.27   +/- 0.42
+FPR95:                 11.22   +/- 0.44
+AUROC:                97.73   +/- 0.08
+AUPR:                   90.32   +/- 0.21

Thank you so much for your time to help!

**Comment by hendrycks** [comment]
Sorry. Places69 was only used for testing the Places365 classifier. The
other models use Places365 test images as OOD data. Earlier I used a subset
of places365_standard/test, and now I have a faster computer so I currently
just randomly sample from places365_standard/test.
