### ISSUE TITLE
Question about Chars74k  dataset as OOD

### ISSUE THREAD

**Issue by igormq** [hendrycks/outlier-exposure#3]
You said in the paper:

``Chars74K is a dataset of photographed characters in various styles; letters such as “O” and “l” were
removed since they can look like numbers''

So, did you also remove the labels between 0 and 9? Because, Chars74k also contains digits (+ uppercase characters and lowercase characters).

Best,
Igor.

**Comment by hendrycks** [comment]
Yes, those were removed too. I'll make note of that in an update to the paper. Thank you.
