### ISSUE TITLE
Using OE for pixel level predictions

### ISSUE THREAD

**Issue by shivamsaboo17** [hendrycks/outlier-exposure#6]
I was going through the paper and in section 3 where the OE minimization objective is defined, there is no constraint on the type of loss that is being used. Hence I was curious if the methodology can be applied to tasks where we do pixel-level prediction (example image translation) and use L1 or L2 loss? Similar to classification loss, if we use uniform random ground truth images as the label for ood images, will it work or dealing with pixel-level predictions, require a completely different methodology?

**Comment by hendrycks** [comment]
It seems plausible that an l1 loss could work for OOD segmentation. (We will likely put up a paper in a month or two proposing a dataset for the task of OOD segmentation.)

**Comment by shivamsaboo17** [comment]
If possible, can you tell me if the labels for segmentation of OOD samples would be random (similar to classification task) or something else?

**Comment by hendrycks** [comment]
I would first try giving anomalies a k+1st class.

**Comment by hendrycks** [comment]
https://github.com/hendrycks/anomaly-seg
