### ISSUE TITLE
80 Million Tiny Images subset for download?

### ISSUE THREAD

**Issue by robintibor** [hendrycks/outlier-exposure#7]
Thanks for sharing the code. I wonder if you can somehow make available a useful subset of 80 million tiny images for faster experimentation? Since you write in the paper "In fact, experiments in this paper often used around 1% of the images in the 80 Million Tiny Images dataset since we only briefly fine-tuned the models."

And then  one would not have to download >200GB :) Would be great.

**Comment by hendrycks** [comment]
One way is to simply download the dataset, and take the first 50k images
(select the first 3072*50000 bytes).
