### ISSUE TITLE
proportion of ODD data in the training sample

### ISSUE THREAD

**Issue by kcharanj** [hendrycks/outlier-exposure#8]
Hi,
Could you please let me know the proportion of "in-distribution" and OOD data points in the training sample?
Thanks

**Comment by hendrycks** [comment]
The code is available. Often the number of outliers in the batch are twice
that of the in-distribution points, so the ratio is often 2 outliers for
every in-distribution example.

**Comment by kcharanj** [comment]
okay, thank you.
